server:
  servlet:
    context-path: /cevaja-api
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:cevajadb
    driver-class-name: org.h2.Driver
    username: lucao
    password: 270787
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true

weather-api-url: https://api.weatherapi.com/v1/current.json?key=7b8fa6a32fab4e5aba7230804231605&q=porto_Alegre